### ISSUE TITLE
Password Strength Indicator with Progress Bar

### ISSUE THREAD

**Issue by AlejandroV01** [AlejandroV01/Ducky#14]
### Issue Title: Password Strength Indicator with Progress Bar

---

**Description**  
- Implement a password strength indicator using the Progress Bar component from `shadcn/ui`.
- The indicator should update dynamically as the user types, providing feedback on the password’s strength (e.g., Weak, Moderate, Strong).
- Password requirements include:
  - Minimum of 6 characters.
  - Should contain numbers.
  - Should contain special characters.
- This feature enhances user experience by giving visual cues on password security requirements.

---

**Task List**  
- [ ] Step 1: Set up the Progress Bar component from `shadcn/ui` to visually represent password strength.
- [ ] Step 2: Define strength levels (e.g., Empty, Weak, Moderate, Strong) based on criteria: minimum of 6 characters, inclusion of numbers, and special characters.
- [ ] Step 3: Add real-time feedback on the criteria met (e.g., checkmarks for fulfilled requirements).
- [ ] Step 4: Style the Progress Bar and accompanying text to match design standards, including color changes based on strength level.

---

**Acceptance Criteria**  
- [ ] The Progress Bar updates dynamically as the user types, reflecting the password’s strength.
- [ ] Visual cues (checkmarks and crosses) indicate which criteria are met or unmet.
- [ ] Strength level (Weak, Moderate, Strong) is displayed with color coding for easy recognition.
- [ ] All relevant tests pass and the feature is reviewed by stakeholders.

---

**Branch Navigation**  
- *Branch Name:* 
`git fetch origin`
`git checkout feature/password-strength-indicator`

---

**Resources / References**  
- [Figma/design link](https://www.figma.com/design/SHU630W8Cn50MfTaLoUPZf/Project-Type?node-id=0-1&t=gCciU4ol2Ykzq4ZP-1)  
- [Notion documentation](https://lying-drill-9f6.notion.site/Fall-24-Web-Dev-Advanced-2-Resource-Page-67eb532ca1a349ebb67214b71f40f4a3?pvs=4)  

---

**Assignee(s)**  
- @duranmichael681 

![image](https://github.com/user-attachments/assets/15e29161-ddd7-433b-84f6-273befdb52d3)
