### ISSUE TITLE
Implement Username Availability Check During Sign-Up

### ISSUE THREAD

**Issue by AlejandroV01** [AlejandroV01/Ducky#18]
### Issue Title: Implement Username Availability Check During Sign-Up

---

**Description**  
- Update the **Sign Up** page to check if a username is already taken during input.  
- This feature enhances user experience by providing immediate feedback, ensuring users can select an available username without submitting the form multiple times.
- To trigger the check, wait for the user to finish typing, then after 2 seconds, hit the `/check-user` API with a POST request. The API will return `{ data: true }` if the username is taken, and `false` otherwise.
- **Inspiration**: Review username availability check features on other popular sites for UX guidance.

---

**Task List**  
- [ ] Step 1: Add a `debounce` function to the username input field to wait 2 seconds after typing stops.
- [ ] Step 2: Set up the `/check-user` POST request:
  ```javascript
  const res = await fetch('http://127.0.0.1:8000/check-user', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ username: 'johndoe' }),
  });
  ```
- [ ] Step 3: Display a message under the username field to indicate if the username is available or already taken.
- [ ] Step 4: Style the feedback message to be clear and visible for the user.

---

**Acceptance Criteria**  
- [ ] The **Sign Up** page dynamically checks username availability with a delay after typing.
- [ ] The API returns `{ data: true }` if the username is taken, `{ data: false }` otherwise, and feedback is displayed accordingly.
- [ ] Feedback is visually clear and user-friendly, with consistent styling.

---

**Branch Navigation**  
- *Branch Name:* 
`git fetch origin`
`git checkout feature/username-availability-check`

---

**Resources / References**  
- [Figma/design link](https://www.figma.com/design/SHU630W8Cn50MfTaLoUPZf/Project-Type?node-id=0-1&t=gCciU4ol2Ykzq4ZP-1)  
- [Notion documentation](https://lying-drill-9f6.notion.site/Fall-24-Web-Dev-Advanced-2-Resource-Page-67eb532ca1a349ebb67214b71f40f4a3?pvs=4)  

---

**Assignee(s)**  
- @AssignedMember
