### ISSUE TITLE
Revamp Authentication to Use Supabase Auth

### ISSUE THREAD

**Issue by AlejandroV01** [AlejandroV01/Ducky#24]
### Issue Title: Revamp Authentication to Use Supabase Auth

---

**Description**  
- Migrate the authentication system of the entire app to use **Supabase Auth**.
- This is crucial to streamline authentication, improve security, and leverage Supabase’s built-in authentication features.

---

**Task List**  
- [x] Step 1: Research and configure Supabase Auth for the project by following [Supabase Auth documentation](https://supabase.com/docs/guides/auth).
- [x] Step 2: Replace existing auth methods with Supabase's email/password and Google
- [x] Step 3: Integrate Supabase Auth into the `/auth` route for **Sign Up** and **Login** pages.
- [x] Step 4: Ensure the integration handles token storage and user sessions correctly.
- [x] Step 5: Update API calls to reflect the new authentication flow.

---

**Acceptance Criteria**  
- [x] Supabase Auth is fully implemented across the app.
- [x] Sign Up, Login, and session handling work smoothly with Supabase.
---

**Branch Navigation**  
git fetch origin
git checkout revamp-auth

---

**Resources / References**  
- [Figma/design link](https://www.figma.com/design/SHU630W8Cn50MfTaLoUPZf/Project-Type?node-id=0-1&t=gCciU4ol2Ykzq4ZP-1)  
- [Notion documentation](https://lying-drill-9f6.notion.site/Fall-24-Web-Dev-Advanced-2-Resource-Page-67eb532ca1a349ebb67214b71f40f4a3?pvs=4)  
- [Supabase Auth Docs](https://supabase.com/docs/guides/auth)

---

**Assignee(s)**  
- @AssignedMember
