### ISSUE TITLE
Create CRUD operations for Users table

### ISSUE THREAD

**Issue by dab1an** [AlejandroV01/Ducky#6]
### Issue Title: *Create CRUD operations for Users table*

---

**Description**  
- Implement CRUD operations for the `user` table.
- This is important to manage user data including registration, updating details, and deleting accounts.

---

**Task List**  
- [ ] Step 1: Create the `POST /users` route to add a new user.
- [ ] Step 2: Create the `GET /users/{id}` route to retrieve user details by `id`.
- [ ] Step 3: Create the `PUT /users/{id}` route to update a user’s details.
- [ ] Step 4: Create the `DELETE /users/{id}` route to remove a user from the database.
- [ ] Step 5: Add validation and error handling for user operations.

---

**Acceptance Criteria**  
- [ ] Users can be created, read, updated, and deleted via API endpoints.
- [ ] Unit tests for all operations are implemented and passing.

---

**Branch Navigation**  
- *Branch Name:* `develop/user-crud`
- `git fetch origin`
- `git checkout user-crud`
---

**Resources / References**  
- Figma: https://www.figma.com/design/SHU630W8Cn50MfTaLoUPZf/Project-Type?node-id=0-1&t=gCciU4ol2Ykzq4ZP-1
- Notion: https://lying-drill-9f6.notion.site/Fall-24-Web-Dev-Advanced-2-Resource-Page-67eb532ca1a349ebb67214b71f40f4a3?pvs=4

---

**Assignee(s)**  
- @franklinnevesfilho 

POST USERS
{
	data: UserObject[],
	error: "",
	statusCode: 200
}

GET USERS
{
	data: UserObject[],
	error: "",
	statusCode: 200
}

PUT USERS
{
	data: UserObject[],
	error: "",
	statusCode: 200
}

DELETE USERS
{
	data: [],
	error: "",
	statusCode: 200
}
